version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-crates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      major-crates:
        patterns:
          - "*"
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
